### ISSUE TITLE
Doesn't work with RRF3?

### ISSUE THREAD

**Issue by nikscha** [iz3man/duet3d#1]
this doesn't seem to work with RRF3, the sensors report unknown value.
printerip/rr_status?type=3 yields a 404 response on RRF3, so I guess it would be necessary to query the object model at printerip/machine/status instead. I don't know how to adapt the YAML though to do that

**Comment by gzawahra** [comment]
hello ! i'm not an expert but you can try changing these lines:
`  - platform: rest
    name: printer Status
    resource: http://ip/rr_status?type=3
    value_template: '{{ value_json.status }}'`
to:
`  - platform: rest
    name: printer Status
    resource: http://ip/machine/status
    value_template: '{{ value_json.status }}'`

i have not tried this yet but will try tomorrow.

**Comment by iz3man** [comment]
![image](https://user-images.githubusercontent.com/11553674/215526475-6e665985-649f-44ba-b9da-aa4c8783f5b9.png)

![image](https://user-images.githubusercontent.com/11553674/215526529-1ecf461d-1a40-4f14-bce3-605eff10cdaa.png)


Works perfectly fine here

![image](https://user-images.githubusercontent.com/11553674/215526779-0b8c928d-9097-4b3c-a99a-cec09f16712d.png)
